### ISSUE TITLE
the stylegan2 implemen

### ISSUE THREAD

**Issue by zhanjiahui** [Jerry2398/Image2StyleGAN-and-Image2StyleGAN-#1]
Your implement of  this paper is petty good !!! I want to ask if it is yourself that completed the source code of styleGAN and styleGAN2 ? If not, **can you tell me where the PyTorch implementation of Stylegan2 comes from?** I'd like to refer to it. Thank you very much.

**Comment by Jerry2398** [comment]
Hello，the Image2StyleGAN++ is implemented based on the Image2styleGAN by me and my teammate. This is our course project but we fail to find the offical implementation of Image2StyleGAN++. The implementation of Image2styleGAN can be found in GitHub. I just modify the code of Image2styleGAN to get a unofficial code of Image2styleGAN++. It should be noted that I just implement partial functions of Image2styleGAN and this implementation is based on my understanding, which may not work very well in some conditions.

Because I am very busy these days and I hope this late response didn't make any trouble for you, if so, I feel very sorry.

Best wishes from Jerry2398.













At 2021-09-09 17:00:32, "JiahuiZhan" ***@***.***> wrote:

Your implement of this paper is petty good !!! I want to ask if it is yourself that completed the source code of styleGAN and styleGAN2 ? If not, can you tell me where the PyTorch implementation of Stylegan2 comes from? I'd like to refer to it. Thank you very much.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
